### ISSUE TITLE
update to deep_merge 1.0.1

### ISSUE THREAD

**Issue by jnankin** [laurilehmijoki/configure-s3-website#12]
My app requires deep_merge 1.0.1 to avoid deprecation warnings such as "warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison."

Can we update the dependency version for s3_website?

**Comment by laurilehmijoki** [comment]
Hello! Can you send a pull request and test the tool with the updated deep_merge lib?

**Comment by jnankin** [comment]
Issued a PR
