### ISSUE TITLE
Don't try to ConfigureS3Website::FileConfigSource.validate_config on an IAM-enabled instance

### ISSUE THREAD

**Issue by sjauld** [laurilehmijoki/configure-s3-website#15]
For our CI builds, we would like to use this gem to create redirects. We shouldn't need to supply s3_id and s3_secret since the machine's IAM role gives it all the permissions it needs.

configure-s3-website/lib/configure-s3-website/config_source/file_config_source.rb line 79 makes our build sad :(

**Comment by laurilehmijoki** [comment]
How would you determine that an IAM role is available?

**Comment by jzuber4** [comment]
This should be resolved by https://github.com/laurilehmijoki/configure-s3-website/pull/22

**Comment by laurilehmijoki** [comment]
Please reopen if needed.
