### ISSUE TITLE
Got an ArgumentError: min_TTL or min_ttl?

### ISSUE THREAD

**Issue by nicluo** [laurilehmijoki/configure-s3-website#17]
$ s3_website cfg apply
    Applying the configurations in s3_website.yml on the AWS services ...
    Bucket xxxxxxxxxxx now functions as a website
    No redirects to configure for xxxxxxxxxxx bucket
    Bucket xxxxxxxxxxx is now readable to the whole world
    Detected an existing CloudFront distribution (id xxxxxxxxxxxxx) ...
    unexpected value at params[:distribution_config][:default_cache_behavior][:minTTL] (ArgumentError)

My s3_website.yml

    cloudfront_distribution_id: <%= ENV['CLOUDFRONT_DISTRIBUTION_ID'] %>
    cloudfront_distribution_config:
      default_cache_behavior:
        min_TTL: <%= 60 * 10 %>
      aliases:
        quantity: 1
        items:
          - <%= ENV['CLOUDFRONT_CNAME_ALIAS'] %>

Changing `min_TTL` to `min_ttl` solved the problem, in the final report:
    
    Applied custom distribution settings:
    ...
      :default_cache_behavior:
        ...
        :min_ttl: 600

Since all the readmes use `min_TTL`, I wonder if my usage could be a misconfiguration on my end? I used the policy at https://github.com/laurilehmijoki/s3_website/blob/master/additional-docs/setting-up-aws-credentials.md to set up the IAM user.

**Comment by laurilehmijoki** [comment]
Please see the breaking changes introduced here: https://github.com/laurilehmijoki/configure-s3-website/blob/master/changelog.md#200

**Comment by nicluo** [comment]
@laurilehmijoki Thanks! Earlier, I had the CNAME format wrong too. Will you be accepting a PR if I just replace the usages in the documentation for this and s3_website? It's the least I can do.

I use s3_website at the end of CI scripts to deploy when Jekyll successfully builds. :)

**Comment by laurilehmijoki** [comment]
Yes, I'd appreciate a PR!
